- src/runs/execution/factory.ts
- src/runs/execution/tools/helpers.ts
Switch to LLaMa for the post-processor. Also modify the prompt -- bee-code-interpreter also supports direct execution of shell code.
> fix(code-interpreter): switch to llama

- src/runs/execution/factory.ts
- src/runs/execution/tools/helpers.ts
This reverts commit 9765bfb60ef81342b77f21340046edfa74e05ab3.
> Revert "fix(code-interpreter): switch to llama (#4)"

- .github/workflows/deployment.yml
Signed-off-by: Tomas Pilar <tomas.pilar@ibm.com>
> chore(CD): deploy via travis

- .env.example
- Dockerfile
- package.json
- pnpm-lock.yaml
> chore(fw): upgrade to v39

- src/opentelemetry.ts
> chore(otel): simplify service name

- workers/python/Dockerfile
> chore(docker): replace python image base

- workers/python/Dockerfile
> chore(build): change base of python dockerfile

- workers/python/python/workers.py
> fix(redis): add healthcheck and more retries to python redis client

- src/runs/runs.service.ts
- src/utils/datetime.ts
- src/vector-store-files/vector-store-files.service.ts
Ref: https://github.com/i-am-bee/internal/issues/16
> chore(quotas): use fixed daily timepoint

- src/utils/datetime.ts
> fix: dayjs import

- .github/workflows/publish-release-image.yml
- workers/python/Dockerfile.docling
- workers/python/Dockerfile.unstructured
- workers/python/poetry.lock
- workers/python/pyproject.toml
- workers/python/python/extraction/extraction.py
> chore(docker): separate docling and unstructured images

- package.json
- pnpm-lock.yaml
- src/chat/chat.service.ts
- src/chat/dtos/chat-completion-create.ts
depends on https://github.com/i-am-bee/bee-agent-framework/pull/207
> feat(chat): constrained decoding support

- package.json
- pnpm-lock.yaml
- src/runs/execution/tools/api-call-tool.ts
- src/runs/execution/tools/file-search-tool.ts
- src/runs/execution/tools/function.ts
- src/runs/execution/tools/read-file-tool.ts
- src/runs/execution/tools/wikipedia-similarity-search-tool.ts
- Namespaces are terms for a discussion.
> feat(deps): upgrade bee-agent-framework

- src/users/dtos/user-create.ts
- src/users/dtos/user-update.ts
- src/users/users.module.ts
- src/users/users.service.ts
> feat(user): make user name modifiable

- src/logger.ts
> fix(logs): make sure errors are visible in elastic

- package.json
- pnpm-lock.yaml
> chore(fw): update to v50

- src/logger.ts
- workers/python/poetry.lock
- workers/python/pyproject.toml
- workers/python/python/extraction/docling.py
> feat(docling): update docling and use hybrid chunker

- .env.example
- workers/python/poetry.lock
- workers/python/pyproject.toml
- workers/python/python/config.py
- workers/python/python/database.py
- workers/python/python/extraction/extraction.py
- workers/python/python/logger.py
- workers/python/python/main.py
- workers/python/python/telemetry.py
- workers/python/python/workers.py
> feat(python): add opentelemetry logs and traces

- workers/python/python/telemetry.py
> fix: otel python disable

- workers/python/python/main.py
- workers/python/python/telemetry.py
> chore(telemetry): improve python telemetry

- package.json
- pnpm-lock.yaml
> chore(fw): upgrade to v52

- workers/python/poetry.lock
- workers/python/pyproject.toml
- workers/python/python/config.py
- workers/python/python/extraction/extraction.py
- workers/python/python/extraction/unstructured.py
> chore(unstructured): upgrade & fix

- workers/python/poetry.lock
- workers/python/pyproject.toml
- workers/python/python/config.py
- workers/python/python/extraction/docling.py
> chore(docling): upgrade to v2.10.0

- src/rate-limit.ts
- src/runs/runs.service.ts
- src/streaming/sse.ts
- src/utils/rate-limit.ts
- src/vector-store-files/vector-store-files.service.ts
> fix(limits): merge window and rate limits, fix streaming headers

- src/users/users.service.ts
https://github.com/i-am-bee/internal/issues/81
> feat(user): add default assistant when user created

- src/users/users.service.ts
https://github.com/i-am-bee/internal/issues/81
> feat(user): update default assistant for new users

- src/chat/chat.module.ts
- src/chat/chat.service.ts
- src/chat/dtos/chat-completion-chunk.ts
- src/chat/dtos/chat-completion-create.ts
- src/embeddings/dtos/embeddings-create.ts
- src/embeddings/dtos/embeddings.ts
- src/embeddings/embeddings.module.ts
- src/embeddings/embeddings.service.ts
- src/embeddings/entities/embeddings.entity.ts
- src/server.ts
- src/streaming/pubsub.ts
- src/streaming/sse.ts
> feat: streaming and embeddings support

- src/tools/dtos/tool-update.ts
- src/tools/tools.service.ts
> fix(tools): encrypt updated api keys

- .github/workflows/main.yml
error: https://github.com/i-am-bee/bee-api/actions/runs/13109433535/job/36634779718#step:6:285
https://vercel.com/guides/corepack-errors-github-actions
> chore: fix corepack version
